source $HOME/.vim/config/settings.vim
source $HOME/.vim/config/plugins.vim
source $HOME/.vim/config/appearance.vim
source $HOME/.vim/config/plugins/fzf.vim
source $HOME/.vim/config/plugins/nerdtree.vim
source $HOME/.vim/config/plugins/vim-commentary.vim
source $HOME/.vim/config/plugins/coc-explorer.vim
source $HOME/.vim/config/plugins/coc.vim
