#!/usr/bin/env sh

wid=$1

get_xorg_attribute() {
    xprop -id "$wid" | grep $1 | awk -F= '{print $2}' | xargs
}

name=$(get_xorg_attribute "_NET_WM_NAME(UTF8_STRING)")
role=$(get_xorg_attribute "WM_WINDOW_ROLE(STRING)")

[[ "$name" =~ .*"Emulator".* ]] \
    && echo state=floating

[[ "$name" =~ .*"win0".* ]] \
    && echo state=floating

[[ "$role" =~ "pop-up" ]] \
    && echo state=floating
