#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
launch-polybar bspwm  &

bspc monitor -d 1 2 3 4 5 6 7 8 9 

bspc config border_width         1
bspc config window_gap           2 

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

#bspc config normal_border_color "#1a1b26"
#bspc config focused_border_color "#1a1b26"
#bspc config presel_feedback_color "#1a1b26"

#bspc config normal_border_color	"#4c566a"
# bspc config active_border_color	"#1e1e1e"
# bspc config focused_border_color "#327bd1"
#bspc config presel_feedback_color	"#327bd1"
#bspc config urgent_border_color "#dd2727"

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Nitrogen state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a flameshot state=floating
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a Qalculate-gtk state=floating
bspc rule -a i7z-gui state=floating
bspc rule -a Sxiv state=floating
bspc rule -a File-roller state=floating
bspc rule -a Emacs state=tiled

bspc rule -a Brave-browser desktop='^1'
bspc rule -a firefox desktop='^1'

bspc config external_rules_command "$(which external_rules)"

