#! /bin/sh

launch-polybar &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6  

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config focused_border_color "#2E3440"
bspc config normal_border_color "#2E3440"

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emulator state=floating
bspc rule -a Nitrogen state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a SimpleScreenRecorder state=floating
bspc rule -a Qalculate-gtk state=floating
bspc rule -a mpv state=fullscreen

